# -*- coding: utf-8 -*-
"""Final_Deliverable(Monthly).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gIbmQ_WoOpmPVZGhqtYDX1RbYv9KGVj-

## Loading the Data
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib.ticker import FuncFormatter
from statsmodels.tsa.holtwinters import SimpleExpSmoothing
from statsmodels.tsa.holtwinters import ExponentialSmoothing
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_percentage_error
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv1D, MaxPooling1D, Flatten, Dense
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

!pip install statsmodels

# Import the data file
file_path = '/content/combined_data_final.xlsx'
combined_df = pd.read_excel(file_path)

combined_df.head()

"""## Fiscal Year Adjustment"""

# Month to number mapping for easier computation
month_to_num = {
    'Jan': 1, 'Feb': 2, 'Mar': 3, 'Apr': 4, 'May': 5, 'Jun': 6,
    'Jul': 7, 'Aug': 8, 'Sep': 9, 'Oct': 10, 'Nov': 11, 'Dec': 12
}
num_to_month = {v: k for k, v in month_to_num.items()}

# Function to calculate fiscal month, fiscal year, and fiscal date
def calculate_fiscal_date(row):
    month_num = month_to_num[row['calendar_month']]
    fiscal_month_num = (month_num + 3 - 1) % 12 + 1  # Shift by 3 months
    fiscal_year = row['calendar_year'] + (1 if fiscal_month_num <= 3 else 0)  # Adjust year if fiscal month is Jan-Mar
    fiscal_month = num_to_month[fiscal_month_num]
    fiscal_date = pd.Timestamp(year=fiscal_year, month=fiscal_month_num, day=1)  # Create first day of fiscal month
    return pd.Series([fiscal_month, fiscal_year, fiscal_date])

# Apply the transformation
combined_df[['fiscal_month', 'fiscal_year', 'fiscal_date']] = combined_df.apply(calculate_fiscal_date, axis=1)

# Display the transformed DataFrame
print(combined_df)

# Calculate total_textile, total_niche, total_commodity, total_services, and total_military_resale
combined_df['total_textile'] = combined_df.filter(like='textile').sum(axis=1)
combined_df['total_niche'] = combined_df.filter(like='niche').sum(axis=1)
combined_df['total_commodity'] = combined_df.filter(like='commodity').sum(axis=1)
combined_df['total_services'] = combined_df.filter(like='service').sum(axis=1)
combined_df['total_military_resale'] = combined_df.filter(like='military_resale').sum(axis=1)

combined_df.columns

new_combined_df = combined_df[['textile_organizational_clothing',
       'textile_uniforms', 'textile_commercial',
       'textile_organizational_equipment', 'niche_n_medical',
       'niche_industrial,_organizational_and_tools', 'niche_personal_safety',
       'niche_n_food_service', 'niche_hazardous_materials',
       'commodity_writing_instruments', 'commodity_commercial',
       'commodity_c_food_service', 'commodity_mro',
       'commodity_office_products', 'commodity_household_item',
       'commodity_c_medical', 'commodity_jansan',
       'service_contract_management_support', 'service_supply_chain',
       'service_508_assurance', 'service_teleservices',
       'service_document_management', 'service_commercial',
       'service_administrative', 'military_resale_military_resale',
       'fiscal_month', 'fiscal_year', 'total_textile', 'total_niche',
       'total_commodity', 'total_services', 'total_military_resale',
       'fiscal_date']]

"""## Performing Exponential Smoothing"""

# Define the sales columns to smooth
sales_columns = ['textile_organizational_clothing',
       'textile_uniforms', 'textile_commercial',
       'textile_organizational_equipment', 'niche_n_medical',
       'niche_industrial,_organizational_and_tools', 'niche_personal_safety',
       'niche_n_food_service', 'niche_hazardous_materials',
       'commodity_writing_instruments', 'commodity_commercial',
       'commodity_c_food_service', 'commodity_mro',
       'commodity_office_products', 'commodity_household_item',
       'commodity_c_medical', 'commodity_jansan',
       'service_contract_management_support', 'service_supply_chain',
       'service_508_assurance', 'service_teleservices',
       'service_document_management', 'service_commercial',
       'service_administrative', 'military_resale_military_resale', 'total_textile', 'total_niche',
       'total_commodity', 'total_services', 'total_military_resale']

# Assuming `new_combined_df` is your original DataFrame with monthly data
# Ensure `fiscal_date` is a datetime type
new_combined_df['fiscal_date'] = pd.to_datetime(new_combined_df['fiscal_date'])

# Aggregate monthly data to monthly level
quarterly_df = new_combined_df.set_index('fiscal_date').resample('M').sum().reset_index()

# Create a smoothed DataFrame for monthly data
smoothed_df = quarterly_df.copy()

# Apply exponential smoothing to each sales category on monthly data
for column in sales_columns:
    model = SimpleExpSmoothing(smoothed_df[column], initialization_method="legacy-heuristic")
    fit = model.fit(smoothing_level=0.2, optimized=False)  # Set smoothing level (0.2 in this example)
    smoothed_df[column] = fit.fittedvalues

# Plot original vs smoothed for each sales category on monthly data
for column in sales_columns:
    plt.figure(figsize=(12, 6))

    # Plot original monthly data
    plt.plot(quarterly_df['fiscal_date'], quarterly_df[column], label=f"{column} (Original Monthly)", color='blue', alpha=0.6)

    # Plot smoothed monthly data
    plt.plot(smoothed_df['fiscal_date'], smoothed_df[column], label=f"{column} (Smoothed Monthly)", color='red', linestyle='--', alpha=0.8)

    # Customize the plot
    plt.title(f"Original vs Smoothed Monthly Sales for {column}", fontsize=16)
    plt.xlabel("Fiscal Date (Monthly)", fontsize=12)
    plt.ylabel("Sales (USD)", fontsize=12)
    plt.legend()
    plt.grid(True)

    # Format y-axis as USD
    from matplotlib.ticker import FuncFormatter
    def usd_formatter(x, pos):
        return f"${x:,.0f}"
    plt.gca().yaxis.set_major_formatter(FuncFormatter(usd_formatter))

    # Show the plot
    plt.show()

"""## Removing the Effect of Covid"""

# Define the sales columns to process
sales_columns = ['textile_organizational_clothing',
       'textile_uniforms', 'textile_commercial',
       'textile_organizational_equipment', 'niche_n_medical',
       'niche_industrial,_organizational_and_tools', 'niche_personal_safety',
       'niche_n_food_service', 'niche_hazardous_materials',
       'commodity_writing_instruments', 'commodity_commercial',
       'commodity_c_food_service', 'commodity_mro',
       'commodity_office_products', 'commodity_household_item',
       'commodity_c_medical', 'commodity_jansan',
       'service_contract_management_support', 'service_supply_chain',
       'service_508_assurance', 'service_teleservices',
       'service_document_management', 'service_commercial',
       'service_administrative', 'military_resale_military_resale', 'total_textile', 'total_niche',
       'total_commodity', 'total_services', 'total_military_resale']

# Define periods
pre_covid_data = smoothed_df[smoothed_df['fiscal_date'] <= '2020-02-29']
covid_data = smoothed_df[(smoothed_df['fiscal_date'] > '2020-02-29') & (smoothed_df['fiscal_date'] <= '2022-06-30')]
post_covid_data = smoothed_df[smoothed_df['fiscal_date'] > '2022-06-30']

# Create a new DataFrame to store de-COVIDed results
de_covid_df = pd.DataFrame({'fiscal_date': smoothed_df['fiscal_date']})

# Process each sales column
for column in sales_columns:
    # Step 1: Train Holt-Winters model on pre-COVID data
    seasonal_periods = 12  # Assuming monthly data with yearly seasonality
    hw_model_pre_covid = ExponentialSmoothing(
        pre_covid_data[column],
        trend='add',
        seasonal='add',
        seasonal_periods=seasonal_periods
    ).fit()

    # Step 2: Forecast for the COVID period
    forecasted_covid_sales = hw_model_pre_covid.forecast(len(covid_data))

    # Step 3: Stitch the data together
    combined_column_data = pd.concat([
        pre_covid_data[[column]],
        pd.Series(forecasted_covid_sales.values, index=covid_data.index, name=column),
        post_covid_data[[column]]
    ])

    # Step 4: Add to the new DataFrame
    de_covid_df[column] = combined_column_data.reset_index(drop=True)

sales_columns = ['textile_organizational_clothing',
       'textile_uniforms', 'textile_commercial',
       'textile_organizational_equipment', 'niche_n_medical',
       'niche_industrial,_organizational_and_tools', 'niche_personal_safety',
       'niche_n_food_service', 'niche_hazardous_materials',
       'commodity_writing_instruments', 'commodity_commercial',
       'commodity_c_food_service', 'commodity_mro',
       'commodity_office_products', 'commodity_household_item',
       'commodity_c_medical', 'commodity_jansan',
       'service_contract_management_support', 'service_supply_chain',
       'service_508_assurance', 'service_teleservices',
       'service_document_management', 'service_commercial',
       'service_administrative', 'military_resale_military_resale', 'total_textile', 'total_niche',
       'total_commodity', 'total_services', 'total_military_resale']

# Plot for each category
for category in sales_columns:
    plt.figure(figsize=(10, 6))
    plt.plot(smoothed_df['fiscal_date'], smoothed_df[category], label=f'Original Smoothed {category}', color='blue', alpha=0.6)
    plt.plot(de_covid_df['fiscal_date'], de_covid_df[category], label=f'De-COVIDed {category}', color='green', linestyle='--')
    plt.title(f'Original vs De-COVIDed Smoothed Data for {category}')
    plt.xlabel('Fiscal Date')
    plt.ylabel('Sales (USD)')
    plt.legend()
    plt.grid(True)
    plt.show()

# Save the final version of data file
de_covid_df.head()

"""## CNN"""

# Step 1: Preprocess the data
# Convert "Date" to datetime format and set as index
de_covid_df['fiscal_date'] = pd.to_datetime(de_covid_df['fiscal_date'])
de_covid_df.set_index('fiscal_date', inplace=True)

# Name the Sub-LoB list
sales_columns = ['textile_organizational_clothing',
       'textile_uniforms', 'textile_commercial',
       'textile_organizational_equipment', 'niche_n_medical',
       'niche_industrial,_organizational_and_tools', 'niche_personal_safety',
       'niche_n_food_service', 'niche_hazardous_materials',
       'commodity_writing_instruments', 'commodity_commercial',
       'commodity_c_food_service', 'commodity_mro',
       'commodity_office_products', 'commodity_household_item',
       'commodity_c_medical', 'commodity_jansan',
       'service_contract_management_support', 'service_supply_chain',
       'service_508_assurance', 'service_teleservices',
       'service_document_management', 'service_commercial',
       'service_administrative', 'military_resale_military_resale', 'total_textile', 'total_niche',
       'total_commodity', 'total_services', 'total_military_resale']

for i in sales_columns:
  # Use only "Train" type data for modeling
  train_data = de_covid_df[i]

  # Scale the data
  scaler = MinMaxScaler(feature_range=(0, 1))
  scaled_data = scaler.fit_transform(train_data.values.reshape(-1, 1))

  # Step 2: Create sequences
  def create_sequences(data, n_steps):
      X, y = [], []
      for i in range(len(data) - n_steps):
          X.append(data[i:i + n_steps])
          y.append(data[i + n_steps])
      return np.array(X), np.array(y)

  n_steps = 12  # Use 12 months for forecasting
  X, y = create_sequences(scaled_data, n_steps)

  # Step 3: Train-test split (80% train, 20% test)
  train_size = int(0.8 * len(X))
  X_train, X_test = X[:train_size], X[train_size:]
  y_train, y_test = y[:train_size], y[train_size:]

  # Reshape the data to fit the model input requirements
  X_train = X_train.reshape((X_train.shape[0], X_train.shape[1], 1))
  X_test = X_test.reshape((X_test.shape[0], X_test.shape[1], 1))

  # Step 4: Define the CNN model
  model = Sequential([
      Conv1D(filters=32, kernel_size=3, activation='relu', input_shape=(n_steps, 1)),
      MaxPooling1D(pool_size=2),
      Flatten(),
      Dense(16, activation='relu'),
      Dense(1)
  ])

  model.compile(optimizer='adam', loss='mean_squared_error')

  # Step 5: Train the model
  history = model.fit(X_train, y_train, epochs=50, batch_size=16, verbose=1)

  # Step 6: Forecast for the test period
  y_pred = model.predict(X_test).flatten()

  # Inverse transform the predictions and actuals
  y_pred = scaler.inverse_transform(y_pred.reshape(-1, 1)).flatten()
  y_test = scaler.inverse_transform(y_test.reshape(-1, 1)).flatten()

  # Step 7: Calculate evaluation metrics
  mae = mean_absolute_error(y_test, y_pred)
  rmse = np.sqrt(mean_squared_error(y_test, y_pred))
  mape = np.mean(np.abs((y_test - y_pred) / y_test)) * 100
  r2 = r2_score(y_test, y_pred)

  # Print evaluation metrics
  print(f"MAE: {mae}")
  print(f"RMSE: {rmse}")
  print(f"MAPE: {mape}%")
  print(f"R²: {r2}")

  # Step 8: Plot actual vs forecasted values
  plt.figure(figsize=(12, 6))

  # Plot the training data
  train_index = train_data.index[:train_size + n_steps]
  test_index = train_data.index[train_size + n_steps:]

  plt.plot(train_index, scaler.inverse_transform(scaled_data[:train_size + n_steps]), label='Train Data', color='blue')

  # Plot the test data and predictions
  plt.plot(test_index, y_test, label='Test Data', color='green')
  plt.plot(test_index, y_pred, label='Forecasted Sales (CNN)', color='red', linestyle='--')

  # Customize plot
  plt.title(f'Actual {i} vs Forecasted Sales using CNN {i}')
  plt.xlabel('Date')
  plt.ylabel('Sales')
  plt.legend()
  plt.grid(True)
  plt.show()

# CNN Final On Monthly

# Step 1: Preprocess the data
# Convert "Date" to datetime format and set as index
# de_covid_df['fiscal_date'] = pd.to_datetime(de_covid_df['fiscal_date'])
# de_covid_df.set_index('fiscal_date', inplace=True)

# Initialize an empty DataFrame to store all future forecasts
future_df = pd.DataFrame()

# Loop through each sales column
for i in sales_columns:
    # Use all data for training
    train_data = de_covid_df[i]

    # Scale the data
    scaler = MinMaxScaler(feature_range=(0, 1))
    scaled_data = scaler.fit_transform(train_data.values.reshape(-1, 1))

    # Step 2: Create sequences
    def create_sequences(data, n_steps):
        X, y = [], []
        for j in range(len(data) - n_steps):
            X.append(data[j:j + n_steps])
            y.append(data[j + n_steps])
        return np.array(X), np.array(y)

    n_steps = 12  # Use 12 months for forecasting
    X, y = create_sequences(scaled_data, n_steps)

    # Reshape the data to fit the model input requirements
    X = X.reshape((X.shape[0], X.shape[1], 1))

    # Step 3: Define the CNN model
    model = Sequential([
        Conv1D(filters=32, kernel_size=3, activation='relu', input_shape=(n_steps, 1)),
        MaxPooling1D(pool_size=2),
        Flatten(),
        Dense(16, activation='relu'),
        Dense(1)
    ])
    model.compile(optimizer='adam', loss='mean_squared_error')

    # Step 4: Train the model using all available data
    model.fit(X, y, epochs=50, batch_size=16, verbose=1)

    # Step 5: Forecast for the next 24 months
    future_steps = 24
    future_predictions = []

    # Use the last n_steps from the scaled data as the starting point
    last_sequence = scaled_data[-n_steps:].reshape(1, n_steps, 1)

    for _ in range(future_steps):
        # Predict the next value
        next_value = model.predict(last_sequence).flatten()[0]
        future_predictions.append(next_value)

        # Update the sequence with the predicted value
        last_sequence = np.append(last_sequence[:, 1:, :], [[[next_value]]], axis=1)

    # Inverse transform the future predictions to the original scale
    future_predictions = scaler.inverse_transform(np.array(future_predictions).reshape(-1, 1)).flatten()

    # Generate future dates starting from the last date in the dataset
    last_date = de_covid_df.index[-1]
    future_dates = pd.date_range(start=last_date, periods=future_steps + 1, freq='M')[1:]

    # Save the future predictions for the current column in a temporary DataFrame
    temp_df = pd.DataFrame({'Fiscal Date': future_dates, f'Forecasted Sales {i}': future_predictions})

    # Merge the temporary DataFrame with the master `future_df`
    if future_df.empty:
        future_df = temp_df
    else:
        future_df = pd.merge(future_df, temp_df, on='Fiscal Date', how='outer')

    # Plot actual data and future predictions
    plt.figure(figsize=(12, 6))

    # Plot the actual data
    plt.plot(de_covid_df.index, train_data, label='Actual Data', color='blue')

    # Plot the future predictions
    plt.plot(future_dates, future_predictions, label='Future Predictions (Next 2 Years)', color='orange', linestyle='--')

    # Customize the plot
    plt.title(f'Actual vs Future Forecast for {i}')
    plt.xlabel('Fiscal Date')
    plt.ylabel('Sales')
    plt.legend()
    plt.grid(True)
    plt.show()

# Print the combined DataFrame with future predictions
print("Combined Future Forecast DataFrame:\n", future_df)

"""## Thank You!"""

future_df.to_csv('future_forecasts.csv', index=False)

